Repository liftedinit/many-framework, pull requests merged in 2022-09, with the labels that each got.

#223 Resiliency tests in CI
  .circleci/config.yml
  docker/e2e/Cargo.nix
  docker/e2e/Makefile
  docker/e2e/docker-compose.jsonnet
  docker/e2e/flake.nix
  tests/e2e/ledger.bats
  tests/e2e/multisig.bats
  tests/e2e/webauthn.bats
  tests/resiliency/catch-up.bats
  tests/resiliency/up-down.bats
  tests/test_helper/ledger.bash
  tests/test_helper/load.bash
  tests/test_helper/many.bash
Labels: enhancement, ci, docker

#227 Fix new nightly clippy and warnings
  src/many-ledger/src/lib.rs
  src/many-ledger/src/main.rs
  src/many-ledger/src/module.rs
  src/many-ledger/src/storage.rs
Labels: bug

#231 Bazel
  .bazelrc
  .gitignore
  BUILD.bazel
  Cargo.Bazel.lock
  Cargo.lock
  WORKSPACE.bazel
  cargo-bazel-lock.json
  src/http_proxy/BUILD.bazel
  src/idstore-export/BUILD.bazel
  src/kvstore/BUILD.bazel
  src/ledger/BUILD.bazel
  src/ledger/Cargo.toml
  src/many-abci/BUILD.bazel
  src/many-kvstore/BUILD.bazel
  src/many-kvstore/tests/common/mod.rs
  src/many-ledger/BUILD.bazel
  src/many-ledger/src/main.rs
  src/many-ledger/src/module.rs
  src/many-ledger/tests/common/mod.rs
Labels: enhancement

#239 Improvements for the E2E Docker on MacOS
  docker/e2e/Makefile
  docker/e2e/build-image.sh
  docker/e2e/generate-cargo-nix.sh
Labels: bug, docker

#242 Rework kvstore
  .circleci/config.yml
  .gitignore
  BUILD.bazel
  Cargo.Bazel.lock
  Cargo.lock
  Cargo.toml
  cargo-bazel-lock.json
  docker/e2e/Cargo.nix
  docker/e2e/Makefile
  docker/e2e/Makefile.common
  docker/e2e/Makefile.kvstore
  docker/e2e/Makefile.ledger
  docker/e2e/docker-compose-kvstore.jsonnet
  docker/e2e/docker-compose-ledger.jsonnet
  docker/e2e/flake.nix
  docker/e2e/kvstore_state.json
  scripts/run.sh
  src/http_proxy/Cargo.toml
  src/kvstore/Cargo.toml
  src/kvstore/src/main.rs
  src/ledger/Cargo.toml
  src/many-abci/BUILD.bazel
  src/many-abci/Cargo.toml
  src/many-kvstore/BUILD.bazel
  src/many-kvstore/Cargo.toml
  src/many-kvstore/build.rs
  src/many-kvstore/src/error.rs
  src/many-kvstore/src/main.rs
  src/many-kvstore/src/module.rs
  src/many-kvstore/src/module/account.rs
  src/many-kvstore/src/module/event.rs
  src/many-kvstore/src/storage.rs
  src/many-kvstore/src/storage/account.rs
  src/many-kvstore/src/storage/event.rs
  src/many-kvstore/tests/account.rs
  src/many-kvstore/tests/common/mod.rs
  src/many-kvstore/tests/events.rs
  src/many-kvstore/tests/kvstore.rs
  src/many-kvstore/tests/kvstore_account.rs
  src/many-kvstore/tests/storage.rs
  src/many-ledger/BUILD.bazel
  src/many-ledger/Cargo.toml
  src/many-ledger/src/main.rs
  staging/kvstore_state.json
  staging/kvstore_state.json5
  tests/e2e/kvstore.bats
  tests/e2e/ledger.bats
  tests/e2e/multisig.bats
  tests/e2e/webauthn.bats
  tests/resiliency/kvstore/catch-up.bats
  tests/resiliency/kvstore/up-down.bats
  tests/resiliency/ledger/catch-up.bats
  tests/resiliency/ledger/up-down.bats
  tests/test_helper/account.bash
  tests/test_helper/kvstore.bash
  tests/test_helper/ledger.bash
  tests/test_helper/load.bash
Labels: enhancement

#247 Fix call to `many-kvstore` in `run.sh` script
  scripts/run.sh
Labels: bug
