Repository liftedinit/many-framework, pull requests merged in 2022-08, with the labels that each got.

#210 Fix catch-up issue
  .circleci/config.yml
  src/many-ledger/Cargo.toml
  src/many-ledger/src/lib.rs
  src/many-ledger/src/main.rs
  src/many-ledger/src/migration.rs
  src/many-ledger/src/migration/block_9400.rs
  src/many-ledger/src/storage.rs
Labels: bug

#209 Faster Docker dev environment
  Cargo.lock
  docker/e2e/.gitignore
  docker/e2e/Cargo.nix
  docker/e2e/Makefile
  docker/e2e/build-image.sh
  docker/e2e/chaos.sh
  docker/e2e/docker-compose.jsonnet
  docker/e2e/flake.lock
  docker/e2e/flake.nix
  docker/e2e/generate-cargo-nix.sh
  src/many-abci/Cargo.toml
  src/many-abci/src/module.rs
Labels: docker

#176 BATs tests in CI
  .circleci/config.yml
  tests/e2e/ledger.bats
  tests/e2e/multisig.bats
  tests/e2e/webauthn.bats
  tests/test_helper/many.bash
Labels: enhancement

#218 Fix bats test when using ci cache
  .circleci/config.yml
Labels: bug

#217 Update to latest `many-rs`
  .circleci/config.yml
  Cargo.lock
  src/http_proxy/Cargo.toml
  src/idstore-export/Cargo.toml
  src/idstore-export/src/main.rs
  src/kvstore/Cargo.toml
  src/ledger/Cargo.toml
  src/many-abci/Cargo.toml
  src/many-kvstore/Cargo.toml
  src/many-kvstore/src/module.rs
  src/many-kvstore/src/storage.rs
  src/many-ledger/Cargo.toml
  src/many-ledger/src/module.rs
  src/many-ledger/src/storage.rs
  src/many-ledger/tests/common/mod.rs
  src/many-ledger/tests/iterator.rs
  src/many-ledger/tests/multisig.rs
Labels: bug, security

#220 Set CircleCI resource class
  .circleci/config.yml
Labels: enhancement, ci
