Repository liftedinit/many-framework, pull requests merged in 2022-06, with the labels that each got.

#115 AccountModule tests
  Cargo.lock
  src/http_proxy/Cargo.toml
  src/kvstore/Cargo.toml
  src/ledger/Cargo.toml
  src/many-abci/Cargo.toml
  src/many-kvstore/Cargo.toml
  src/many-ledger/Cargo.toml
  src/many-ledger/src/module.rs
  src/many-ledger/src/storage.rs
  src/many-ledger/tests/account.rs
  src/many-ledger/tests/common.rs
  src/many-ledger/tests/idstore.rs
Labels: enhancement

#121 Properly serialize and sign errors from transport to Tendermint
  Cargo.lock
  src/many-abci/src/many_app.rs
Labels: bug, alpha

#123 Allow for a way to disable webauthn checks for testing
  src/many-ledger/Cargo.toml
  src/many-ledger/src/main.rs
  src/many-ledger/src/module.rs
Labels: enhancement

#126 Add a shasum file to releases
  .github/workflows/release.yml
Labels: enhancement

#128 Add ID in Error ResponseMessage
  Cargo.lock
  src/http_proxy/Cargo.toml
  src/kvstore/Cargo.toml
  src/ledger/Cargo.toml
  src/many-abci/Cargo.toml
  src/many-abci/src/many_app.rs
  src/many-kvstore/Cargo.toml
  src/many-ledger/Cargo.toml
Labels: enhancement

#132 Use an OS matrix for CI and release
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: enhancement

#130 Ledger* tests
  Cargo.lock
  Makefile
  src/http_proxy/Cargo.toml
  src/kvstore/Cargo.toml
  src/ledger/Cargo.toml
  src/many-abci/Cargo.toml
  src/many-kvstore/Cargo.toml
  src/many-ledger/Cargo.toml
  src/many-ledger/src/json.rs
  src/many-ledger/src/module.rs
  src/many-ledger/src/storage.rs
  src/many-ledger/tests/account.rs
  src/many-ledger/tests/common/mod.rs
  src/many-ledger/tests/ledger.rs
  src/many-ledger/tests/ledger_commands.rs
  src/many-ledger/tests/ledger_transactions.rs
  src/many-ledger/tests/multisig.rs
Labels: enhancement

#136 Return proper errors
  Cargo.lock
  src/many-ledger/src/error.rs
  src/many-ledger/src/storage.rs
Labels: bug

#134 Webauthn tests
  tests/e2e/webauthn.bats
  tests/test_helper/many.bash
Labels: enhancement

#139 Update to latest `many-rs`
  Cargo.lock
  src/http_proxy/Cargo.toml
  src/kvstore/Cargo.toml
  src/ledger/Cargo.toml
  src/many-abci/Cargo.toml
  src/many-kvstore/Cargo.toml
  src/many-ledger/Cargo.toml
  src/many-ledger/src/json.rs
  src/many-ledger/src/module.rs
  src/many-ledger/tests/account.rs
  src/many-ledger/tests/idstore.rs
  src/many-ledger/tests/ledger_commands.rs
  src/many-ledger/tests/multisig.rs
Labels: bug

#140 Allow accounts to become disabled instead of deleted
  Cargo.lock
  src/http_proxy/Cargo.toml
  src/kvstore/Cargo.toml
  src/ledger/Cargo.toml
  src/ledger/src/multisig.rs
  src/many-abci/Cargo.toml
  src/many-kvstore/Cargo.toml
  src/many-ledger/Cargo.toml
  src/many-ledger/src/main.rs
  src/many-ledger/src/module.rs
  src/many-ledger/src/storage.rs
  src/many-ledger/tests/account.rs
  src/many-ledger/tests/common/mod.rs
  src/many-ledger/tests/events.rs
  src/many-ledger/tests/iterator.rs
  src/many-ledger/tests/multisig.rs
Labels: enhancement, alpha

#142 Account owns account
  src/many-ledger/src/storage.rs
  src/many-ledger/tests/account.rs
  staging/ledger_state.json5
Labels: enhancement

#153 Refactor and improve the run.sh script
  scripts/run.sh
  src/many-abci/src/main.rs
  src/many-ledger/src/main.rs
Labels: enhancement, refactor

#156 Update to a recent version of `many-rs`
  Cargo.lock
  src/http_proxy/Cargo.toml
  src/kvstore/Cargo.toml
  src/ledger/Cargo.toml
  src/many-abci/Cargo.toml
  src/many-kvstore/Cargo.toml
  src/many-ledger/Cargo.toml
Labels: bug

#158 Update to latest `many-rs`
  Cargo.lock
  src/http_proxy/Cargo.toml
  src/kvstore/Cargo.toml
  src/ledger/Cargo.toml
  src/many-abci/Cargo.toml
  src/many-kvstore/Cargo.toml
  src/many-ledger/Cargo.toml
Labels: bug, security
