Repository liftedinit/many-framework, pull requests merged in 2022-07, with the labels that each got.

#147 Test `LedgerStorage` `load()`
  src/many-ledger/tests/storage.rs
Labels: enhancement

#164 Fix storage load test
  src/many-ledger/tests/storage.rs
Labels: bug

#159 Add integration tests to KVStore
  Cargo.lock
  src/many-kvstore/Cargo.toml
  src/many-kvstore/tests/common/mod.rs
  src/many-kvstore/tests/kvstore.rs
Labels: enhancement

#167 Add the feature list to the account module
  src/many-ledger/src/main.rs
  src/many-ledger/src/module.rs
Labels: bug

#168 CircleCI + CodeCov
  .circleci/config.yml
  .github/workflows/audit.yml
  .github/workflows/ci.yml
  .github/workflows/coverage.yml
  .github/workflows/release.yml
Labels: enhancement

#173 Add coverage badge and fix badge links
  README.md
Labels: documentation

#174 Use the right `merk` version
  Cargo.lock
  src/idstore-export/Cargo.toml
Labels: bug, security

#181 Test approving an executed tx
  src/many-ledger/tests/multisig.rs
Labels: enhancement

#185 Fix bad merge
  src/many-ledger/tests/multisig.rs
Labels: bug

#187 Update `merk`
  Cargo.lock
  src/idstore-export/Cargo.toml
  src/many-kvstore/Cargo.toml
  src/many-ledger/Cargo.toml
Labels: bug, security

#190 Release Ubuntu 22.04
  .circleci/config.yml
Labels: enhancement, ci

#172 Error on empty feature
  src/many-ledger/src/module.rs
  src/many-ledger/tests/account.rs
Labels: bug

#195 Rework cache
  .circleci/config.yml
Labels: enhancement, ci

#196 Allow override of tendermint version in make
  docker/e2e/Makefile
  docker/e2e/docker-compose.jsonnet
Labels: enhancement, docker

#194 Update `many-rs` and remove dead code
  Cargo.lock
  src/http_proxy/Cargo.toml
  src/kvstore/Cargo.toml
  src/ledger/Cargo.toml
  src/many-abci/Cargo.toml
  src/many-kvstore/Cargo.toml
  src/many-ledger/Cargo.toml
  src/many-ledger/src/main.rs
  src/many-ledger/src/module.rs
Labels: enhancement

#204 Remove duplicate linkage of ciborium
  .gitignore
  Cargo.lock
  Cargo.toml
  src/many-abci/Cargo.toml
Labels: enhancement
