Repository liftedinit/many-framework, pull requests merged in 2022-10, with the labels that each got.

#253 Use `syslog-tracing` crate instead of git repo
  Cargo.Bazel.lock
  Cargo.lock
  cargo-bazel-lock.json
  docker/e2e/Cargo.nix
  src/http_proxy/Cargo.toml
  src/http_proxy/src/main.rs
  src/kvstore/Cargo.toml
  src/kvstore/src/main.rs
  src/ledger/Cargo.toml
  src/ledger/src/main.rs
  src/many-abci/Cargo.toml
  src/many-abci/src/main.rs
  src/many-kvstore/Cargo.toml
  src/many-kvstore/src/main.rs
  src/many-ledger/Cargo.toml
  src/many-ledger/src/main.rs
Labels: enhancement

#252 ABCI Allow list
  Cargo.lock
  docker/e2e/Cargo.nix
  docker/e2e/Makefile.kvstore
  docker/e2e/Makefile.ledger
  docker/e2e/docker-compose-kvstore.jsonnet
  docker/e2e/docker-compose-ledger.jsonnet
  docker/e2e/generate-allow-addrs.sh
  scripts/run.sh
  src/kvstore/src/main.rs
  src/ledger/src/main.rs
  src/many-abci/Cargo.toml
  src/many-abci/src/main.rs
  src/many-abci/src/many_app.rs
  tests/resiliency/kvstore/abci-allow-addrs.bats
  tests/resiliency/ledger/abci-allow-addrs.bats
  tests/test_helper/kvstore.bash
  tests/test_helper/ledger.bash
Labels: enhancement

#256 Create a release without block migrations
  .circleci/config.yml
Labels: bug, enhancement

#257 Fix release CI
  .circleci/config.yml
Labels: bug

#259 Impl allow-addr in (many-)ledger and kvstore
  .circleci/config.yml
  src/many-kvstore/src/main.rs
  src/many-kvstore/src/module.rs
  src/many-kvstore/src/module/allow_addrs.rs
  src/many-ledger/src/main.rs
  src/many-ledger/src/module.rs
  tests/e2e/kvstore/allow_addrs.bats
  tests/e2e/kvstore/kvstore.bats
  tests/e2e/ledger/allow_addrs.bats
  tests/e2e/ledger/ledger.bats
  tests/e2e/ledger/multisig.bats
  tests/e2e/ledger/webauthn.bats
  tests/e2e/ledger/webauthn_state.json
  tests/test_helper/kvstore.bash
  tests/test_helper/ledger.bash
  tests/test_helper/load.bash
  tests/test_helper/many.bash
Labels: enhancement

#268 Fix new nightly clippy
  src/many-abci/src/module.rs
Labels: bug

#243 Data Attributes
  Cargo.lock
  docker/e2e/Cargo.nix
  docker/e2e/Makefile
  docker/e2e/Makefile.ledger
  docker/e2e/docker-compose-ledger.jsonnet
  docker/e2e/flake.lock
  docker/e2e/flake.nix
  docker/e2e/generate-cargo-nix.sh
  src/many-ledger/Cargo.toml
  src/many-ledger/src/lib.rs
  src/many-ledger/src/main.rs
  src/many-ledger/src/migration.rs
  src/many-ledger/src/migration/data.rs
  src/many-ledger/src/module.rs
  src/many-ledger/src/storage.rs
  src/many-ledger/src/storage/migration_ext/data.rs
  src/many-ledger/src/storage/migration_ext/mod.rs
  src/many-ledger/tests/migration.rs
  tests/resiliency/ledger/data_attribute_migration.bats
  tests/resiliency/ledger/migrations.json5
Labels: enhancement

#270 Fix Bazel build and update `rules_rust` to 0.11.0
  Cargo.Bazel.lock
  Cargo.lock
  WORKSPACE.bazel
  cargo-bazel-lock.json
  src/many-ledger/src/main.rs
Labels: bug

#262 macOS nightly
  .circleci/config.yml
Labels: enhancement, ci

#271 Overwrite existing tag
  .circleci/config.yml
Labels: bug

#272 Attribute specific filter
  Cargo.lock
  docker/e2e/Cargo.nix
  src/http_proxy/Cargo.toml
  src/kvstore/Cargo.toml
  src/ledger/Cargo.toml
  src/many-abci/Cargo.toml
  src/many-kvstore/Cargo.toml
  src/many-ledger/Cargo.toml
  src/many-ledger/src/module.rs
  src/many-ledger/tests/events.rs
Labels: enhancement

#249 Missing blockchain endpoints
  Cargo.lock
  docker/e2e/Cargo.nix
  src/http_proxy/Cargo.toml
  src/kvstore/Cargo.toml
  src/ledger/Cargo.toml
  src/many-abci/Cargo.toml
  src/many-abci/src/module.rs
  src/many-kvstore/Cargo.toml
  src/many-ledger/Cargo.toml
Labels: enhancement

#264 Fix async status return
  Cargo.lock
  docker/e2e/Cargo.nix
  src/http_proxy/Cargo.toml
  src/kvstore/Cargo.toml
  src/kvstore/src/main.rs
  src/ledger/Cargo.toml
  src/ledger/src/main.rs
  src/many-abci/Cargo.toml
  src/many-abci/src/module.rs
  src/many-kvstore/Cargo.toml
  src/many-ledger/Cargo.toml
Labels: bug, breaking change

#274 Fix new nightly clippy
  src/http_proxy/src/main.rs
  src/idstore-export/src/main.rs
  src/kvstore/src/main.rs
  src/ledger/src/main.rs
  src/ledger/src/multisig.rs
  src/many-abci/src/abci_app.rs
  src/many-abci/src/main.rs
  src/many-kvstore/src/main.rs
  src/many-kvstore/src/storage/account.rs
  src/many-ledger/src/json.rs
  src/many-ledger/src/main.rs
  src/many-ledger/src/storage.rs
Labels: bug

#277 Re-add ledger WebAuthn Verifier
  src/many-abci/src/main.rs
  src/many-abci/src/many_app.rs
  src/many-ledger/src/main.rs
Labels: bug

#275 Ledger refactor
  src/many-ledger/src/main.rs
  src/many-ledger/src/migration.rs
  src/many-ledger/src/module.rs
  src/many-ledger/src/module/abci.rs
  src/many-ledger/src/module/account.rs
  src/many-ledger/src/module/allow_addrs.rs
  src/many-ledger/src/module/data.rs
  src/many-ledger/src/module/event.rs
  src/many-ledger/src/module/idstore.rs
  src/many-ledger/src/module/idstore_webauthn.rs
  src/many-ledger/src/module/ledger.rs
  src/many-ledger/src/module/ledger_commands.rs
  src/many-ledger/src/module/multisig.rs
  src/many-ledger/src/storage.rs
  src/many-ledger/src/storage/abci.rs
  src/many-ledger/src/storage/account.rs
  src/many-ledger/src/storage/data.rs
  src/many-ledger/src/storage/event.rs
  src/many-ledger/src/storage/idstore.rs
  src/many-ledger/src/storage/ledger.rs
  src/many-ledger/src/storage/ledger_commands.rs
  src/many-ledger/src/storage/multisig.rs
  src/many-ledger/tests/multisig.rs
Labels: enhancement
